### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by andremeireles** [Jaedsonn/ohmymovies#2]
- The Left and right buttons moves 2 page's unit instead of 1.
- The API gives you 45.876 pages, the website gets only 500 (0 ... 499) without error and the UI shows you **1** of **22476**.
- The Last page button retrieve a page with a position out of the bounds (Page 22475 of undefined) and not changes to disabled. If you click on it again gives you NaN of undefined.
- The UI is not synced with the url pagination. The difference is 1 unit.

**Comment by Jaedsonn** [comment]
Hi Andre, thanks for your feedback! I have been working to solve these problems and have managed to resolve them thanks to your good comments. Later, I will update the page and implement the changes with the solutions.

**Comment by Jaedsonn** [comment]
Issue resolved. Thanks again for feedback

**Comment by andremeireles** [comment]
I'm glad the tips helped.
Just curious. Limiting the last page at 500, is it a design feature or a bug?

**Comment by andremeireles** [comment]
> Hi Andre, thanks for your feedback! I have been working to solve these problems and have managed to resolve them thanks to your good comments. Later, I will update the page and implement the changes with the solutions.

I'm glad the tips helped.
